### ISSUE TITLE
Update to newer SDL version(s)

### ISSUE THREAD

**Issue by eib** [figgis/yuv-viewer#1]
yuv-viewer doesn't compile against the latest SDL version.

**Comment by figgis** [comment]
This code was written for SDL1.2, which is clearly stated. I have a viewer based on the 2.x version that I haven't pushed yet. Give me some time and I can push that version to github as well.

BTW. When you say "doesn't compile against the latest SDL version", please state, which version and add the error-log :-)

**Comment by figgis** [comment]
See https://github.com/figgis/yuv-viewer2 for a viewer based on SDL2
